on: [push, pull_request]
name: Test
jobs:
  test:
    name: Test Go ${{ matrix.go }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: ['1.17', '1.16']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: go test ./...
